import { useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { SEO, breadcrumbSchema } from "@/components/SEO";
import { Slider } from "@/components/ui/slider";
import {
  Upload, DollarSign, BarChart3, Users, Shield, Zap,
  CheckCircle, ArrowRight, Play, Star, HelpCircle,
  ChevronDown, ChevronUp, ExternalLink, Tv, TrendingUp,
  Award, MessageSquare
} from "lucide-react";

const STEPS = [
  { icon: Users,       title: "Create Your Account",  desc: "Sign up for free and set up your creator profile in minutes. No minimum requirements." },
  { icon: Upload,      title: "Book an Upload Slot",   desc: "Schedule your content slot in our program guide and submit your video for review." },
  { icon: Play,        title: "Go Live or Upload",     desc: "Stream live or upload pre-recorded content. We handle delivery and encoding." },
  { icon: DollarSign,  title: "Earn 70% Revenue",      desc: "Collect 70% of all ad revenue generated by your content, paid monthly." },
];

const STATS = [
  { value: "500+",   label: "Active Creators",    color: "oklch(0.74 0.21 218)" },
  { value: "70%",    label: "Revenue Share",       color: "oklch(0.65 0.22 150)" },
  { value: "$50",    label: "Min. Payout",         color: "oklch(0.78 0.18 60)" },
  { value: "24hrs",  label: "Slot Approval",       color: "oklch(0.65 0.25 290)" },
];

const FAQS = [
  { q: "How does the 70% revenue share work?",
    a: "ZTVLIVE collects all ad revenue from your content and pays you 70% of the net revenue monthly. Payments are processed via PayPal or bank transfer once you reach the $50 minimum threshold." },
  { q: "What types of content can I upload?",
    a: "We accept tech reviews, gaming content, sports commentary, movie reviews, podcasts, news, music performances, and educational content. All content must comply with our Content Guidelines." },
  { q: "How do I book an upload slot?",
    a: "Once signed in, visit your Creator Dashboard and click 'Book Upload Slot'. Choose your preferred date and time, submit your content details, and our team will confirm within 24 hours." },
  { q: "Is there a minimum subscriber or view requirement?",
    a: "No! We welcome creators at all stages. Whether you have 0 or 100,000 followers, you can apply to become a ZTVLIVE creator." },
  { q: "Can I stream live on ZTVLIVE?",
    a: "Yes! Creator Pro subscribers ($14.99/month) get live streaming access. You can go live directly from your YouTube channel and we'll embed it on ZTVLIVE." },
  { q: "What are the content rights?",
    a: "You retain full ownership of your content. ZTVLIVE receives a non-exclusive license to stream and monetize your content on the platform. You can remove your content at any time." },
];

const TESTIMONIALS = [
  { name: "Alex Rivera",  role: "Tech Reviewer",    earnings: "$1,240/mo",  text: "ZTVLIVE gave my channel the exposure it needed. The 70% split is the best I've seen anywhere." },
  { name: "Jasmine Cole", role: "Gaming Creator",   earnings: "$890/mo",    text: "Booking slots is so easy. My audience grew 4x in 3 months and the payouts are always on time." },
  { name: "Marcus Webb",  role: "Sports Analyst",   earnings: "$2,100/mo",  text: "The analytics dashboard is incredible. I know exactly what content performs and when to post." },
];

function EarningsCalculator() {
  const [views, setViews] = useState([50000]);
  const cpm = 3.5;
  const totalRevenue = (views[0]! / 1000) * cpm;
  const creatorRevenue = totalRevenue * 0.7;
  const ztvRevenue = totalRevenue * 0.3;

  return (
    <div className="relative overflow-hidden rounded-2xl p-6 md:p-8
      bg-gradient-to-br from-[oklch(0.65_0.22_150/0.08)] to-[oklch(0.74_0.21_218/0.05)]
      border border-[oklch(0.65_0.22_150/0.2)]">
      <div className="absolute top-0 right-0 w-48 h-48 bg-[oklch(0.65_0.22_150/0.06)] rounded-full -translate-y-1/2 translate-x-1/2 blur-3xl pointer-events-none" />
      <div className="relative">
        <div className="flex items-center gap-2 mb-1">
          <TrendingUp className="w-5 h-5 text-[oklch(0.65_0.22_150)]" />
          <h3 className="text-lg font-black text-white">Earnings Calculator</h3>
        </div>
        <p className="text-white/45 text-sm mb-6">Estimate your monthly earnings based on views</p>

        <div className="mb-6">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-white/60">Monthly Views</span>
            <span className="text-xl font-black text-white">{views[0]!.toLocaleString()}</span>
          </div>
          <Slider value={views} onValueChange={setViews} min={1000} max={1000000} step={1000} className="w-full" />
          <div className="flex justify-between text-xs text-white/25 mt-1.5">
            <span>1K</span><span>500K</span><span>1M</span>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-3 mb-5">
          <div className="text-center p-4 rounded-xl bg-white/5 border border-white/8">
            <p className="text-xs text-white/40 mb-1">Total Revenue</p>
            <p className="text-xl font-black text-white">${totalRevenue.toFixed(0)}</p>
          </div>
          <div className="text-center p-4 rounded-xl bg-[oklch(0.65_0.22_150/0.1)] border border-[oklch(0.65_0.22_150/0.3)]">
            <p className="text-xs text-[oklch(0.65_0.22_150)] mb-1 font-semibold">Your 70%</p>
            <p className="text-xl font-black text-[oklch(0.65_0.22_150)]">${creatorRevenue.toFixed(0)}</p>
          </div>
          <div className="text-center p-4 rounded-xl bg-white/5 border border-white/8">
            <p className="text-xs text-white/40 mb-1">ZTVLIVE 30%</p>
            <p className="text-xl font-black text-white/40">${ztvRevenue.toFixed(0)}</p>
          </div>
        </div>

        <div className="bg-[oklch(0.65_0.22_150/0.08)] border border-[oklch(0.65_0.22_150/0.2)] rounded-xl p-3 text-center">
          <p className="text-xs text-[oklch(0.65_0.22_150)] font-semibold">
            At {views[0]!.toLocaleString()} views/month you could earn
            <span className="text-base font-black ml-1">${creatorRevenue.toFixed(0)}/month</span>
          </p>
        </div>

        <p className="text-[10px] text-white/25 text-center mt-3">
          Based on average CPM of $3.50. Actual earnings vary by content category, audience location, and ad performance.
        </p>
      </div>
    </div>
  );
}

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-white/8 last:border-0">
      <button onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-4 text-left gap-4 hover:text-[oklch(0.74_0.21_218)] transition-colors">
        <span className="text-sm font-semibold text-white">{q}</span>
        {open
          ? <ChevronUp className="w-4 h-4 text-white/40 shrink-0" />
          : <ChevronDown className="w-4 h-4 text-white/40 shrink-0" />}
      </button>
      {open && (
        <div className="pb-4">
          <p className="text-sm text-white/55 leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  );
}

export default function CreatorHub() {
  const { isAuthenticated } = useAuth();
  const schemas = [breadcrumbSchema([{ name: "Home", url: "/" }, { name: "Become a Creator", url: "/creator" }])];

  return (
    <>
      <SEO
        title="Become a Creator — Earn 70% Revenue Share on ZTVLIVE"
        description="Join ZTVLIVE as a creator. Upload your content, build your audience, and earn 70% revenue share. Free to join. No minimum requirements."
        url="/creator"
        schema={schemas}
      />

      <div className="min-h-screen bg-background">
        {/* ── HERO ──────────────────────────────────── */}
        <div className="relative overflow-hidden pt-12 pb-20">
          {/* Background */}
          <div className="absolute inset-0 bg-gradient-to-b from-[oklch(0.65_0.22_150/0.06)] via-transparent to-transparent pointer-events-none" />
          <div className="absolute top-0 left-1/3 w-96 h-96 bg-[oklch(0.65_0.22_150/0.05)] rounded-full blur-3xl pointer-events-none" />
          <div className="absolute top-0 right-1/3 w-96 h-96 bg-[oklch(0.74_0.21_218/0.05)] rounded-full blur-3xl pointer-events-none" />

          <div className="relative max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              {/* Left: copy */}
              <div>
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full
                  bg-[oklch(0.65_0.22_150/0.1)] border border-[oklch(0.65_0.22_150/0.3)]
                  text-[oklch(0.65_0.22_150)] text-sm font-bold mb-6">
                  <Star className="w-4 h-4" />
                  500+ Active Creators
                </div>
                <h1 className="text-5xl md:text-6xl font-black text-white mb-5 leading-tight">
                  Create.<br />Stream.<br />
                  <span className="bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.74_0.21_218)] bg-clip-text text-transparent">
                    Earn 70%.
                  </span>
                </h1>
                <p className="text-lg text-white/55 mb-8 leading-relaxed">
                  Join ZTVLIVE's creator network and earn{" "}
                  <strong className="text-white">70% revenue share</strong> on every view.
                  No minimum requirements. Free to join. Start earning from day one.
                </p>
                <div className="flex items-center gap-4 flex-wrap">
                  {isAuthenticated ? (
                    <Link href="/creator/book-slot">
                      <button className="flex items-center gap-2 px-8 py-3.5 rounded-xl
                        bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.74_0.21_218)]
                        text-white font-black text-sm hover:opacity-90 active:scale-95 transition-all
                        shadow-xl shadow-[oklch(0.65_0.22_150/0.3)]">
                        <Upload className="w-4 h-4" />
                        Book Upload Slot
                      </button>
                    </Link>
                  ) : (
                    <button onClick={() => (window.location.href = getLoginUrl())}
                      className="flex items-center gap-2 px-8 py-3.5 rounded-xl
                        bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.74_0.21_218)]
                        text-white font-black text-sm hover:opacity-90 active:scale-95 transition-all
                        shadow-xl shadow-[oklch(0.65_0.22_150/0.3)]">
                      Get Started — Free
                      <ArrowRight className="w-4 h-4" />
                    </button>
                  )}
                  <Link href="/creator/dashboard">
                    <button className="flex items-center gap-2 px-6 py-3.5 rounded-xl
                      border border-white/15 text-white/70 hover:text-white hover:border-white/30
                      font-semibold text-sm transition-all">
                      <BarChart3 className="w-4 h-4" />
                      Creator Dashboard
                    </button>
                  </Link>
                </div>
              </div>

              {/* Right: stats grid */}
              <div className="grid grid-cols-2 gap-4">
                {STATS.map((stat) => (
                  <div key={stat.label}
                    className="glass-card p-6 text-center hover:border-white/20 transition-all">
                    <div className="text-4xl font-black mb-1" style={{ color: stat.color }}>{stat.value}</div>
                    <div className="text-sm text-white/45">{stat.label}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* ── HOW IT WORKS ──────────────────────────── */}
        <div className="bg-gradient-to-b from-transparent via-[oklch(0.74_0.21_218/0.03)] to-transparent py-16">
          <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-10">
              <h2 className="text-3xl font-black text-white mb-3">How It Works</h2>
              <p className="text-white/45">Four simple steps to start earning</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
              {STEPS.map((step, i) => (
                <div key={i} className="relative glass-card p-6 hover:border-white/20 transition-all group">
                  <div className="absolute -top-3.5 -left-3.5 w-8 h-8 rounded-full
                    bg-gradient-to-br from-[oklch(0.74_0.21_218)] to-[oklch(0.56_0.24_290)]
                    flex items-center justify-center text-sm font-black text-white shadow-lg">
                    {i + 1}
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-[oklch(0.74_0.21_218/0.1)] border border-[oklch(0.74_0.21_218/0.2)]
                    flex items-center justify-center mb-4">
                    <step.icon className="w-6 h-6 text-[oklch(0.74_0.21_218)]" />
                  </div>
                  <h3 className="text-sm font-black text-white mb-2 group-hover:text-[oklch(0.74_0.21_218)] transition-colors">{step.title}</h3>
                  <p className="text-xs text-white/50 leading-relaxed">{step.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── EARNINGS CALCULATOR ───────────────────── */}
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
            <div>
              <h2 className="text-3xl font-black text-white mb-4">Transparent Monetization</h2>
              <p className="text-white/55 leading-relaxed mb-6">
                ZTVLIVE operates on a transparent{" "}
                <strong className="text-white">70/30 revenue split</strong>. You keep 70% of all
                advertising revenue generated by your content. We handle ad sales, delivery
                infrastructure, and monthly payments.
              </p>
              <div className="space-y-3">
                {[
                  { label: "Ad Revenue Share",   value: "70%",           color: "oklch(0.65 0.22 150)" },
                  { label: "Monthly Payouts",     value: "PayPal / Bank", color: "oklch(0.74 0.21 218)" },
                  { label: "Minimum Payout",      value: "$50",           color: "oklch(0.78 0.18 60)" },
                  { label: "Payment Schedule",    value: "Net 30",        color: "oklch(0.65 0.25 290)" },
                ].map((item) => (
                  <div key={item.label}
                    className="flex items-center justify-between p-3.5 rounded-xl bg-white/4 border border-white/8 hover:bg-white/6 transition-colors">
                    <span className="text-sm text-white/65">{item.label}</span>
                    <span className="text-sm font-black" style={{ color: item.color }}>{item.value}</span>
                  </div>
                ))}
              </div>
            </div>
            <EarningsCalculator />
          </div>
        </div>

        {/* ── CREATOR TESTIMONIALS ──────────────────── */}
        <div className="bg-gradient-to-b from-transparent via-[oklch(0.56_0.24_290/0.03)] to-transparent py-16">
          <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-black text-white text-center mb-3">Creator Success Stories</h2>
            <p className="text-white/45 text-center mb-10">Real creators, real earnings</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {TESTIMONIALS.map((t) => (
                <div key={t.name} className="glass-card p-6 hover:border-white/20 transition-all">
                  <div className="flex items-center justify-between mb-4">
                    <div className="flex">
                      {[...Array(5)].map((_, i) => (
                        <Star key={i} className="w-3.5 h-3.5 text-yellow-400 fill-yellow-400" />
                      ))}
                    </div>
                    <div className="text-sm font-black text-[oklch(0.65_0.22_150)]">{t.earnings}</div>
                  </div>
                  <p className="text-sm text-white/65 leading-relaxed mb-4">"{t.text}"</p>
                  <div>
                    <div className="text-sm font-bold text-white">{t.name}</div>
                    <div className="text-xs text-white/40">{t.role}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── DASHBOARD PREVIEW ─────────────────────── */}
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-black text-white mb-3">Creator Dashboard</h2>
            <p className="text-white/45">Everything you need to manage your content and earnings</p>
          </div>
          <div className="glass-card rounded-2xl p-6 md:p-8">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              {[
                { label: "Total Views",   value: "124,500",  icon: BarChart3,  color: "oklch(0.74 0.21 218)" },
                { label: "This Month",    value: "$312.40",  icon: DollarSign, color: "oklch(0.65 0.22 150)" },
                { label: "Subscribers",  value: "2,840",    icon: Users,      color: "oklch(0.65 0.25 290)" },
                { label: "Videos Live",  value: "18",       icon: Play,       color: "oklch(0.78 0.18 60)" },
              ].map((stat) => (
                <div key={stat.label}
                  className="text-center p-4 rounded-xl bg-white/4 border border-white/8 hover:bg-white/7 transition-colors">
                  <div className="w-9 h-9 rounded-lg flex items-center justify-center mx-auto mb-2"
                    style={{ background: `${stat.color}15` }}>
                    <stat.icon className="w-4.5 h-4.5" style={{ color: stat.color }} />
                  </div>
                  <p className="text-lg font-black text-white">{stat.value}</p>
                  <p className="text-xs text-white/40 mt-0.5">{stat.label}</p>
                </div>
              ))}
            </div>
            <div className="flex flex-col sm:flex-row gap-3">
              <Link href="/creator/dashboard" className="flex-1">
                <button className="w-full py-3 rounded-xl bg-[oklch(0.74_0.21_218)] text-[oklch(0.06_0.012_264)] font-black text-sm flex items-center justify-center gap-2 hover:opacity-90 active:scale-95 transition-all">
                  <BarChart3 className="w-4 h-4" />
                  Open Dashboard
                </button>
              </Link>
              <Link href="/creator/book-slot" className="flex-1">
                <button className="w-full py-3 rounded-xl border border-white/15 text-white/70 hover:text-white hover:border-white/30 font-semibold text-sm flex items-center justify-center gap-2 transition-all">
                  <Upload className="w-4 h-4" />
                  Book Upload Slot
                </button>
              </Link>
            </div>
          </div>
        </div>

        {/* ── GUIDELINES + SUPPORT ──────────────────── */}
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 pb-16">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Guidelines */}
            <div>
              <h2 className="text-2xl font-black text-white mb-5">Upload Guidelines</h2>
              <div className="space-y-2.5">
                {[
                  { ok: true,  text: "Original content you own the rights to" },
                  { ok: true,  text: "HD quality (720p minimum, 1080p preferred)" },
                  { ok: true,  text: "Tech, gaming, sports, movies, podcasts, news, music" },
                  { ok: true,  text: "Family-friendly or clearly labeled mature content" },
                  { ok: false, text: "Copyrighted music or video without license" },
                  { ok: false, text: "Misleading titles, thumbnails, or descriptions" },
                  { ok: false, text: "Hate speech, harassment, or harmful content" },
                  { ok: false, text: "Spam, repetitive, or low-effort content" },
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-white/3 border border-white/6">
                    <CheckCircle className="w-4 h-4 shrink-0"
                      style={{ color: item.ok ? "oklch(0.65 0.22 150)" : "oklch(0.6 0.22 25)" }} />
                    <span className="text-sm text-white/65">{item.text}</span>
                  </div>
                ))}
              </div>
              <div className="flex gap-3 mt-5">
                <Link href="/content-guidelines">
                  <button className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-white/15 text-white/60 hover:text-white hover:border-white/30 text-xs font-semibold transition-all">
                    <Shield className="w-3.5 h-3.5" />
                    Content Guidelines
                  </button>
                </Link>
                <Link href="/creator/rights">
                  <button className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-white/15 text-white/60 hover:text-white hover:border-white/30 text-xs font-semibold transition-all">
                    Rights & Legal
                    <ExternalLink className="w-3 h-3" />
                  </button>
                </Link>
              </div>
            </div>

            {/* Support */}
            <div>
              <h2 className="text-2xl font-black text-white mb-5">Creator Support</h2>
              <div className="space-y-3">
                {[
                  { icon: Zap,           title: "24/7 Creator Support",    desc: "Email and chat support for all creators",                color: "oklch(0.74 0.21 218)" },
                  { icon: Users,         title: "Creator Discord",          desc: "Join our community of 500+ creators",                   color: "oklch(0.65 0.25 290)" },
                  { icon: BarChart3,     title: "Analytics Dashboard",      desc: "Real-time views, earnings, and audience data",          color: "oklch(0.65 0.22 150)" },
                  { icon: Shield,        title: "Content Protection",       desc: "DMCA protection and content ID system",                 color: "oklch(0.78 0.18 60)" },
                  { icon: MessageSquare, title: "Creator Community Forum",  desc: "Share tips, collaborate, and grow together",            color: "oklch(0.72 0.2 25)" },
                  { icon: Award,         title: "Creator Spotlight",        desc: "Top creators featured on the ZTVLIVE homepage",         color: "oklch(0.7 0.18 200)" },
                ].map((item) => (
                  <div key={item.title}
                    className="flex items-start gap-3 p-3.5 rounded-xl bg-white/4 border border-white/8 hover:bg-white/6 transition-colors">
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0"
                      style={{ background: `${item.color}15`, border: `1px solid ${item.color}25` }}>
                      <item.icon className="w-4 h-4" style={{ color: item.color }} />
                    </div>
                    <div>
                      <p className="text-sm font-bold text-white">{item.title}</p>
                      <p className="text-xs text-white/45">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
              <a href="https://discord.gg/ztvlive" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex">
                <button className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[oklch(0.65_0.25_290)] text-white font-bold text-sm hover:opacity-90 active:scale-95 transition-all">
                  <ExternalLink className="w-4 h-4" />
                  Join Creator Discord
                </button>
              </a>
            </div>
          </div>
        </div>

        {/* ── FAQ ───────────────────────────────────── */}
        <div className="bg-gradient-to-b from-transparent via-[oklch(0.74_0.21_218/0.03)] to-transparent py-16">
          <div className="max-w-2xl mx-auto px-4">
            <div className="text-center mb-8">
              <HelpCircle className="w-8 h-8 text-[oklch(0.74_0.21_218)] mx-auto mb-3" />
              <h2 className="text-2xl font-black text-white mb-2">Creator FAQ</h2>
              <p className="text-white/45 text-sm">Everything you need to know before joining</p>
            </div>
            <div className="glass-card rounded-2xl px-6">
              {FAQS.map((faq, i) => (
                <FAQItem key={i} q={faq.q} a={faq.a} />
              ))}
            </div>
          </div>
        </div>

        {/* ── FINAL CTA ─────────────────────────────── */}
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 pb-16">
          <div className="relative overflow-hidden rounded-3xl p-10 text-center
            bg-gradient-to-r from-[oklch(0.65_0.22_150/0.12)] via-[oklch(0.74_0.21_218/0.08)] to-[oklch(0.65_0.22_150/0.12)]
            border border-[oklch(0.65_0.22_150/0.25)]">
            <div className="absolute inset-0 bg-gradient-to-b from-transparent to-[oklch(0.08_0.012_264/0.4)] pointer-events-none" />
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-96 h-48
              bg-gradient-radial from-[oklch(0.65_0.22_150/0.1)] to-transparent pointer-events-none" />
            <div className="relative">
              <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-[oklch(0.65_0.22_150)] to-[oklch(0.74_0.21_218)]
                flex items-center justify-center mx-auto mb-5 shadow-xl shadow-[oklch(0.65_0.22_150/0.3)]">
                <Tv className="w-8 h-8 text-white" />
              </div>
              <h2 className="text-3xl font-black text-white mb-3">Ready to start earning?</h2>
              <p className="text-white/55 mb-6 max-w-md mx-auto">
                Join 500+ creators already earning on ZTVLIVE. No minimum requirements. Free to join.
                <strong className="text-white"> 70% revenue share from day one.</strong>
              </p>
              <div className="flex items-center justify-center gap-4 flex-wrap">
                {isAuthenticated ? (
                  <Link href="/creator/book-slot">
                    <button className="flex items-center gap-2 px-8 py-3.5 rounded-xl
                      bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.74_0.21_218)]
                      text-white font-black text-sm hover:opacity-90 active:scale-95 transition-all
                      shadow-xl shadow-[oklch(0.65_0.22_150/0.3)]">
                      Book Your First Upload Slot
                      <ArrowRight className="w-4 h-4" />
                    </button>
                  </Link>
                ) : (
                  <button onClick={() => (window.location.href = getLoginUrl())}
                    className="flex items-center gap-2 px-8 py-3.5 rounded-xl
                      bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.74_0.21_218)]
                      text-white font-black text-sm hover:opacity-90 active:scale-95 transition-all
                      shadow-xl shadow-[oklch(0.65_0.22_150/0.3)]">
                    Create Free Account
                    <ArrowRight className="w-4 h-4" />
                  </button>
                )}
                <Link href="/subscribe">
                  <button className="flex items-center gap-2 px-6 py-3.5 rounded-xl
                    border border-white/15 text-white/70 hover:text-white hover:border-white/30
                    font-semibold text-sm transition-all">
                    View Creator Pro Plan
                    <ArrowRight className="w-4 h-4" />
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
