import { Link } from "wouter";
import { SEO, breadcrumbSchema } from "@/components/SEO";
import { ArrowLeft } from "lucide-react";

export default function CreatorRights() {
  const schemas = [breadcrumbSchema([{ name: "Home", url: "/" }, { name: "Creator Hub", url: "/creator" }, { name: "Rights & Legal", url: "/creator/rights" }])];
  return (
    <>
      <SEO title="Creator Rights & Legal Agreement" description="ZTVLIVE creator rights and legal agreement. Understand your content ownership, revenue share terms, and platform policies." url="/creator/rights" schema={schemas} />
      <div className="max-w-3xl mx-auto px-4 py-8">
        <Link href="/creator" className="inline-flex items-center gap-2 text-white/40 hover:text-white text-sm mb-6 transition-colors">
          <ArrowLeft className="w-4 h-4" />Back to Creator Hub
        </Link>
        <h1 className="text-3xl font-black text-white mb-2">Creator Rights & Legal Agreement</h1>
        <p className="text-white/40 text-sm mb-8">Last updated: January 1, 2025</p>
        <div className="prose prose-invert prose-sm max-w-none space-y-6">
          {[
            { title: "1. Content Ownership", body: "You retain full ownership of all content you upload to ZTVLIVE. By uploading content, you grant ZTVLIVE a non-exclusive, worldwide, royalty-free license to stream, display, and monetize your content on the ZTVLIVE platform and its distribution partners." },
            { title: "2. Revenue Share", body: "ZTVLIVE pays creators 70% of net advertising revenue generated by their content. 'Net revenue' means gross ad revenue minus platform fees, payment processing fees, and applicable taxes. Revenue is calculated monthly and paid within 30 days of the month end." },
            { title: "3. Content Standards", body: "All content must comply with ZTVLIVE's Content Guidelines and Community Guidelines. Content that violates these guidelines may be removed without notice. Repeated violations may result in account termination." },
            { title: "4. DMCA Compliance", body: "ZTVLIVE complies with the Digital Millennium Copyright Act (DMCA). If you believe your copyrighted work has been infringed, please submit a DMCA takedown notice. Creators who repeatedly upload infringing content will have their accounts terminated." },
            { title: "5. Termination", body: "Either party may terminate this agreement with 30 days written notice. Upon termination, your content will be removed from the platform within 7 business days. Any earned but unpaid revenue will be paid within 60 days of termination." },
            { title: "6. Indemnification", body: "You agree to indemnify and hold harmless ZTVLIVE, its officers, directors, employees, and agents from any claims, damages, or expenses arising from your content or your use of the platform." },
            { title: "7. Governing Law", body: "This agreement is governed by the laws of the State of Florida, United States. Any disputes shall be resolved through binding arbitration in accordance with the American Arbitration Association rules." },
          ].map((section) => (
            <div key={section.title} className="glass-card rounded-xl p-5">
              <h2 className="text-base font-bold text-white mb-2">{section.title}</h2>
              <p className="text-sm text-white/60 leading-relaxed">{section.body}</p>
            </div>
          ))}
        </div>
        <div className="mt-8 glass-card rounded-xl p-4 border-[oklch(0.72_0.2_220/0.2)]">
          <p className="text-xs text-white/50">Questions about creator rights? Contact us at <a href="mailto:creators@ztvlivestream.com" className="text-[oklch(0.72_0.2_220)] hover:underline">creators@ztvlivestream.com</a></p>
        </div>
      </div>
    </>
  );
}
