import { useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { SEO, breadcrumbSchema } from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import {
  Upload,
  DollarSign,
  BarChart3,
  Users,
  Shield,
  Zap,
  CheckCircle,
  ArrowRight,
  Play,
  Star,
  HelpCircle,
  ChevronDown,
  ChevronUp,
  ExternalLink,
} from "lucide-react";

const STEPS = [
  { icon: Users, title: "Create Your Account", desc: "Sign up for free and set up your creator profile in minutes." },
  { icon: Upload, title: "Book an Upload Slot", desc: "Schedule your content slot in our program guide and submit your video." },
  { icon: Play, title: "Go Live or Upload", desc: "Stream live or upload pre-recorded content. We handle delivery and encoding." },
  { icon: DollarSign, title: "Earn 70% Revenue", desc: "Collect 70% of all ad revenue generated by your content, paid monthly." },
];

const FAQS = [
  {
    q: "How does the 70% revenue share work?",
    a: "ZTVLIVE collects all ad revenue from your content and pays you 70% of the net revenue monthly. Payments are processed via PayPal or bank transfer once you reach the $50 minimum threshold.",
  },
  {
    q: "What types of content can I upload?",
    a: "We accept tech reviews, gaming content, sports commentary, movie reviews, podcasts, news, music performances, and educational content. All content must comply with our Content Guidelines.",
  },
  {
    q: "How do I book an upload slot?",
    a: "Once signed in, visit your Creator Dashboard and click 'Book Upload Slot'. Choose your preferred date and time, submit your content details, and our team will confirm within 24 hours.",
  },
  {
    q: "Is there a minimum subscriber or view requirement?",
    a: "No! We welcome creators at all stages. Whether you have 0 or 100,000 followers, you can apply to become a ZTVLIVE creator.",
  },
  {
    q: "Can I stream live on ZTVLIVE?",
    a: "Yes! Creator Pro subscribers ($14.99/month) get live streaming access. You can go live directly from your YouTube channel and we'll embed it on ZTVLIVE.",
  },
  {
    q: "What are the content rights?",
    a: "You retain full ownership of your content. ZTVLIVE receives a non-exclusive license to stream and monetize your content on the platform. You can remove your content at any time.",
  },
];

function EarningsCalculator() {
  const [views, setViews] = useState([50000]);
  const cpm = 3.5; // average CPM
  const totalRevenue = (views[0]! / 1000) * cpm;
  const creatorRevenue = totalRevenue * 0.7;
  const ztvRevenue = totalRevenue * 0.3;

  return (
    <div className="glass-card rounded-2xl p-6 md:p-8">
      <h3 className="text-xl font-bold text-white mb-2">Creator Earnings Calculator</h3>
      <p className="text-white/50 text-sm mb-6">Estimate your monthly earnings based on monthly views</p>

      <div className="mb-6">
        <div className="flex items-center justify-between mb-3">
          <span className="text-sm text-white/70">Monthly Views</span>
          <span className="text-lg font-bold text-white">{views[0]!.toLocaleString()}</span>
        </div>
        <Slider
          value={views}
          onValueChange={setViews}
          min={1000}
          max={1000000}
          step={1000}
          className="w-full"
        />
        <div className="flex justify-between text-xs text-white/30 mt-1">
          <span>1K</span>
          <span>1M</span>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="text-center p-4 rounded-xl bg-white/5 border border-white/10">
          <p className="text-xs text-white/40 mb-1">Total Revenue</p>
          <p className="text-lg font-black text-white">${totalRevenue.toFixed(0)}</p>
        </div>
        <div className="text-center p-4 rounded-xl bg-[oklch(0.65_0.22_150/0.1)] border border-[oklch(0.65_0.22_150/0.3)]">
          <p className="text-xs text-[oklch(0.65_0.22_150)] mb-1">Your Earnings (70%)</p>
          <p className="text-lg font-black text-[oklch(0.65_0.22_150)]">${creatorRevenue.toFixed(0)}</p>
        </div>
        <div className="text-center p-4 rounded-xl bg-white/5 border border-white/10">
          <p className="text-xs text-white/40 mb-1">ZTVLIVE (30%)</p>
          <p className="text-lg font-black text-white/50">${ztvRevenue.toFixed(0)}</p>
        </div>
      </div>

      <p className="text-xs text-white/30 text-center">
        Based on average CPM of $3.50. Actual earnings vary by content category, audience location, and ad performance.
      </p>
    </div>
  );
}

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-white/10 last:border-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-4 text-left gap-4"
      >
        <span className="text-sm font-medium text-white">{q}</span>
        {open ? (
          <ChevronUp className="w-4 h-4 text-white/40 shrink-0" />
        ) : (
          <ChevronDown className="w-4 h-4 text-white/40 shrink-0" />
        )}
      </button>
      {open && (
        <div className="pb-4">
          <p className="text-sm text-white/60 leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  );
}

export default function CreatorHub() {
  const { isAuthenticated } = useAuth();

  const schemas = [breadcrumbSchema([{ name: "Home", url: "/" }, { name: "Become a Creator", url: "/creator" }])];

  return (
    <>
      <SEO
        title="Become a Creator — Earn 70% Revenue Share"
        description="Join ZTVLIVE as a creator. Upload your content, build your audience, and earn 70% revenue share. Free to join. No minimum requirements."
        url="/creator"
        schema={schemas}
      />

      <div className="max-w-[1400px] mx-auto px-4 md:px-6">
        {/* Hero */}
        <div className="relative py-20 text-center overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-[oklch(0.65_0.22_150/0.05)] to-transparent" />
          <div className="relative z-10">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[oklch(0.65_0.22_150/0.1)] border border-[oklch(0.65_0.22_150/0.3)] text-[oklch(0.65_0.22_150)] text-sm font-semibold mb-6">
              <Star className="w-4 h-4" />
              500+ Active Creators
            </div>
            <h1 className="text-4xl md:text-6xl font-black text-white mb-4">
              Create. Stream. <span className="gradient-text">Earn.</span>
            </h1>
            <p className="text-white/60 text-lg max-w-xl mx-auto mb-8">
              Join ZTVLIVE's creator network and earn <strong className="text-white">70% revenue share</strong> on every view. No minimum requirements. Free to join.
            </p>
            <div className="flex items-center justify-center gap-4 flex-wrap">
              {isAuthenticated ? (
                <Link href="/creator/book-slot">
                  <Button className="bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.72_0.2_220)] text-white border-0 font-bold px-8 py-3 text-base">
                    <Upload className="w-5 h-5 mr-2" />
                    Book Upload Slot
                  </Button>
                </Link>
              ) : (
                <Button
                  onClick={() => (window.location.href = getLoginUrl())}
                  className="bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.72_0.2_220)] text-white border-0 font-bold px-8 py-3 text-base"
                >
                  Get Started — Free
                  <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              )}
              <Link href="/creator/dashboard">
                <Button variant="outline" className="border-white/20 text-white hover:bg-white/10 font-semibold px-8 py-3 text-base">
                  <BarChart3 className="w-5 h-5 mr-2" />
                  Creator Dashboard
                </Button>
              </Link>
            </div>
          </div>
        </div>

        {/* How It Works */}
        <section className="py-12 border-t border-white/5">
          <div className="text-center mb-10">
            <div className="section-divider mx-auto" />
            <h2 className="text-2xl font-bold text-white mb-2">How It Works</h2>
            <p className="text-white/50 text-sm">Four simple steps to start earning</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {STEPS.map((step, i) => (
              <div key={i} className="glass-card rounded-2xl p-6 text-center relative">
                <div className="absolute -top-3 -left-3 w-7 h-7 rounded-full bg-[oklch(0.72_0.2_220)] flex items-center justify-center text-xs font-black text-[oklch(0.08_0.01_264)]">
                  {i + 1}
                </div>
                <div className="w-12 h-12 rounded-xl bg-[oklch(0.72_0.2_220/0.1)] flex items-center justify-center mx-auto mb-4 border border-[oklch(0.72_0.2_220/0.2)]">
                  <step.icon className="w-6 h-6 text-[oklch(0.72_0.2_220)]" />
                </div>
                <h3 className="text-sm font-bold text-white mb-2">{step.title}</h3>
                <p className="text-xs text-white/50 leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Earnings Calculator */}
        <section className="py-12 border-t border-white/5">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
            <div>
              <div className="section-divider" />
              <h2 className="text-2xl font-bold text-white mb-3">Monetization Overview</h2>
              <p className="text-white/60 text-sm leading-relaxed mb-6">
                ZTVLIVE operates on a transparent <strong className="text-white">70/30 revenue split</strong>. You keep 70% of all advertising revenue generated by your content. We handle the ad sales, delivery infrastructure, and payments.
              </p>
              <div className="space-y-3">
                {[
                  { label: "Ad Revenue Share", value: "70%", color: "oklch(0.65 0.22 150)" },
                  { label: "Monthly Payouts", value: "PayPal / Bank", color: "oklch(0.72 0.2 220)" },
                  { label: "Minimum Payout", value: "$50", color: "oklch(0.75 0.18 60)" },
                  { label: "Payment Schedule", value: "Net 30", color: "oklch(0.65 0.25 290)" },
                ].map((item) => (
                  <div key={item.label} className="flex items-center justify-between p-3 rounded-xl bg-white/5 border border-white/10">
                    <span className="text-sm text-white/70">{item.label}</span>
                    <span className="text-sm font-bold" style={{ color: item.color }}>{item.value}</span>
                  </div>
                ))}
              </div>
            </div>
            <EarningsCalculator />
          </div>
        </section>

        {/* Dashboard Preview */}
        <section className="py-12 border-t border-white/5">
          <div className="text-center mb-8">
            <div className="section-divider mx-auto" />
            <h2 className="text-2xl font-bold text-white mb-2">Creator Dashboard</h2>
            <p className="text-white/50 text-sm">Everything you need to manage your content and earnings</p>
          </div>
          <div className="glass-card rounded-2xl p-6 md:p-8">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              {[
                { label: "Total Views", value: "124,500", icon: BarChart3, color: "oklch(0.72 0.2 220)" },
                { label: "This Month", value: "$312.40", icon: DollarSign, color: "oklch(0.65 0.22 150)" },
                { label: "Subscribers", value: "2,840", icon: Users, color: "oklch(0.65 0.25 290)" },
                { label: "Videos Live", value: "18", icon: Play, color: "oklch(0.75 0.18 60)" },
              ].map((stat) => (
                <div key={stat.label} className="text-center p-4 rounded-xl bg-white/5 border border-white/10">
                  <stat.icon className="w-5 h-5 mx-auto mb-2" style={{ color: stat.color }} />
                  <p className="text-lg font-black text-white">{stat.value}</p>
                  <p className="text-xs text-white/40 mt-0.5">{stat.label}</p>
                </div>
              ))}
            </div>
            <div className="flex flex-col sm:flex-row gap-3">
              <Link href="/creator/dashboard" className="flex-1">
                <Button className="w-full bg-[oklch(0.72_0.2_220)] text-[oklch(0.08_0.01_264)] font-bold hover:opacity-90">
                  <BarChart3 className="w-4 h-4 mr-2" />
                  Open Dashboard
                </Button>
              </Link>
              <Link href="/creator/book-slot" className="flex-1">
                <Button variant="outline" className="w-full border-white/20 text-white hover:bg-white/10">
                  <Upload className="w-4 h-4 mr-2" />
                  Book Upload Slot
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* Upload Guidelines */}
        <section className="py-12 border-t border-white/5">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div>
              <div className="section-divider" />
              <h2 className="text-2xl font-bold text-white mb-3">Upload Guidelines</h2>
              <div className="space-y-3">
                {[
                  { ok: true, text: "Original content you own the rights to" },
                  { ok: true, text: "HD quality (720p minimum, 1080p preferred)" },
                  { ok: true, text: "Tech, gaming, sports, movies, podcasts, news, music" },
                  { ok: true, text: "Family-friendly or clearly labeled mature content" },
                  { ok: false, text: "Copyrighted music or video without license" },
                  { ok: false, text: "Misleading titles, thumbnails, or descriptions" },
                  { ok: false, text: "Hate speech, harassment, or harmful content" },
                  { ok: false, text: "Spam, repetitive, or low-effort content" },
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <CheckCircle
                      className="w-4 h-4 shrink-0"
                      style={{ color: item.ok ? "oklch(0.65 0.22 150)" : "oklch(0.6 0.22 25)" }}
                    />
                    <span className="text-sm text-white/70">{item.text}</span>
                  </div>
                ))}
              </div>
              <div className="mt-4 flex gap-3">
                <Link href="/content-guidelines">
                  <Button variant="outline" size="sm" className="border-white/20 text-white hover:bg-white/10 text-xs">
                    <Shield className="w-3.5 h-3.5 mr-1.5" />
                    Full Content Guidelines
                  </Button>
                </Link>
                <Link href="/creator/rights">
                  <Button variant="outline" size="sm" className="border-white/20 text-white hover:bg-white/10 text-xs">
                    Rights & Legal
                    <ExternalLink className="w-3 h-3 ml-1.5" />
                  </Button>
                </Link>
              </div>
            </div>

            <div>
              <div className="section-divider" />
              <h2 className="text-2xl font-bold text-white mb-3">Creator Support</h2>
              <div className="space-y-3">
                {[
                  { icon: Zap, title: "24/7 Creator Support", desc: "Email and chat support for all creators", color: "oklch(0.72 0.2 220)" },
                  { icon: Users, title: "Creator Discord", desc: "Join our community of 500+ creators", color: "oklch(0.65 0.25 290)" },
                  { icon: BarChart3, title: "Analytics Dashboard", desc: "Real-time views, earnings, and audience data", color: "oklch(0.65 0.22 150)" },
                  { icon: Shield, title: "Content Protection", desc: "DMCA protection and content ID system", color: "oklch(0.75 0.18 60)" },
                ].map((item) => (
                  <div key={item.title} className="flex items-start gap-3 p-3 rounded-xl bg-white/5 border border-white/10">
                    <div
                      className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                      style={{ background: `${item.color}15`, border: `1px solid ${item.color}30` }}
                    >
                      <item.icon className="w-4 h-4" style={{ color: item.color }} />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-white">{item.title}</p>
                      <p className="text-xs text-white/50">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
              <a
                href="https://discord.gg/ztvlive"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-4 inline-flex"
              >
                <Button className="bg-[oklch(0.65_0.25_290)] text-white border-0 font-semibold text-sm hover:opacity-90">
                  <ExternalLink className="w-4 h-4 mr-2" />
                  Join Creator Discord
                </Button>
              </a>
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="py-12 border-t border-white/5">
          <div className="max-w-2xl mx-auto">
            <div className="text-center mb-8">
              <HelpCircle className="w-8 h-8 text-[oklch(0.72_0.2_220)] mx-auto mb-3" />
              <h2 className="text-2xl font-bold text-white mb-2">Creator FAQ</h2>
              <p className="text-white/50 text-sm">Everything you need to know before joining</p>
            </div>
            <div className="glass-card rounded-2xl px-6">
              {FAQS.map((faq, i) => (
                <FAQItem key={i} q={faq.q} a={faq.a} />
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-16 text-center border-t border-white/5">
          <h2 className="text-3xl font-black text-white mb-3">Ready to start earning?</h2>
          <p className="text-white/50 text-sm mb-8 max-w-md mx-auto">
            Join 500+ creators already earning on ZTVLIVE. No minimum requirements. Free to join. 70% revenue share from day one.
          </p>
          {isAuthenticated ? (
            <Link href="/creator/book-slot">
              <Button className="bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.72_0.2_220)] text-white border-0 font-bold px-10 py-3 text-base">
                Book Your First Upload Slot
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </Link>
          ) : (
            <Button
              onClick={() => (window.location.href = getLoginUrl())}
              className="bg-gradient-to-r from-[oklch(0.65_0.22_150)] to-[oklch(0.72_0.2_220)] text-white border-0 font-bold px-10 py-3 text-base"
            >
              Create Free Account
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
          )}
        </section>
      </div>
    </>
  );
}
